#端口号
server:
  port: 2026

spring:
  #datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  #重复bean名配置
  main:
    allow-bean-definition-overriding: true

#mybatis-plus
mybatis-plus:
  #xml扫描路径，可配置多个
  mapper-locations:
    - classpath:com/xmz/**/*.xml
    - classpath:com/other/**/*.xml
  #别名包扫描，多个用逗号分割，mybatis中不需要再写具体路径
  type-aliases-package: com.xmz.**.entity, com.other.**.domain
  #打开SqlRunner
  global-config:
    enable-sql-runner: true

#日志配置
logging:
  level:
    #日志打印级别（配置此处会覆盖logback的配置）：key为包路径，如果要配置整个项目key为：root
    #root: info
    com.xmz: debug
    com.other: debug
  file:
    #日志文件输出路径（配置此处会覆盖logback的配置）
    path: D:/1/logs